[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
hook_add = 'source ~/.config/nvim/plugins/coc_settings.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'mechatroner/rainbow_csv'

